Repository arana-db/kiwi, pull requests merged in 2024-10, with the labels that each got.

#34 fix: configure go test of kiwi
  etc/conf/kiwi.conf
  etc/script/kiwitests.sh
  src/base_cmd.cc
  src/cmd_thread_pool_worker.cc
  src/config.h
  src/pstd/memory_file.h
  src/replication.cc
  src/storage/src/storage.cc
  tests/admin_test.go
  tests/kiwi_suite_test.go
Labels: ☢️ Bug, 🧹 Updates

#57 fix: ctest execute fail，remove duplicate ci
  .github/workflows/import_braft.yml
  .github/workflows/pikiwidb.yml
Labels: ☢️ Bug, 🧹 Updates

#49 fix: build info not add to code, put the git information in cmake
  CMakeLists.txt
  etc/script/build.sh
  src/kiwi.cc
Labels: ✏️ Feature, ☢️ Bug

#62 fix: ci run on macos-12
  .github/workflows/pikiwidb.yml
Labels: ☢️ Bug

#58 fix: String2int error
  src/pstd/pstd_string.h
  src/storage/include/storage/util.h
  src/storage/src/redis_hashes.cc
  src/storage/src/util.cc
Labels: ☢️ Bug
