Repository arana-db/kiwi, pull requests merged in 2025-04, with the labels that each got.

#17 feat: add readme files
  README.md
  README_CN.md
Labels: 📒 Documentation, ✏️ Feature

#16 feat: implement coding
  src/storage/coding.rs
  src/storage/mod.rs
Labels: ✏️ Feature

#22 feat: impl options helper
  src/storage/mod.rs
  src/storage/options_helper.rs
Labels: ✏️ Feature

#19 feat: add rocksdb dependencies
  .gitignore
  Cargo.lock
  Cargo.toml
Labels: ✏️ Feature, 🤖 Dependencies

#26 fix: update slot indexer
  src/main.rs
  src/storage/mod.rs
  src/storage/slot_indexer.rs
Labels: ☢️ Bug, 🧹 Updates

#29 feat: add lib.rs
  src/lib.rs
  src/main.rs
Labels: ✏️ Feature
